# Generated by Django 4.2.13 on 2024-05-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='draftDone',
            field=models.BooleanField(default=False),
        ),
    ]
