# Generated by Django 4.2.13 on 2024-05-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_league_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='current_week',
            field=models.IntegerField(default=1),
        ),
    ]
