# Generated by Django 4.2.13 on 2024-05-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_league_current_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='next_week_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
