# Generated by Django 4.2.13 on 2024-05-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_leaguemembership_losses_leaguemembership_ties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='draft_order',
            field=models.TextField(default=''),
        ),
    ]
