# Generated by Django 4.2.13 on 2024-05-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_league_draft_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='current_drafter',
            field=models.TextField(default=''),
        ),
    ]
